// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq3YTjB3Ues8ktrJuOmsOUfpjU5AUU7Q8',
    appId: '1:630002783892:web:52d4eea956c08deb8ac681',
    messagingSenderId: '630002783892',
    projectId: 'havealiens-dcf3e',
    authDomain: 'havealiens-dcf3e.firebaseapp.com',
    storageBucket: 'havealiens-dcf3e.appspot.com',
    measurementId: 'G-KPNFGWYBPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KyT-QCe0DCAVs-I4fBPx8sUFjS7sxu8',
    appId: '1:630002783892:android:b6de1664bde9d8868ac681',
    messagingSenderId: '630002783892',
    projectId: 'havealiens-dcf3e',
    storageBucket: 'havealiens-dcf3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-WXS0coLJu8hOmiQoGDTUcS4G1hQeHsI',
    appId: '1:630002783892:ios:9cee1f6d247421488ac681',
    messagingSenderId: '630002783892',
    projectId: 'havealiens-dcf3e',
    storageBucket: 'havealiens-dcf3e.appspot.com',
    iosBundleId: 'com.example.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-WXS0coLJu8hOmiQoGDTUcS4G1hQeHsI',
    appId: '1:630002783892:ios:1db883c63420cf8f8ac681',
    messagingSenderId: '630002783892',
    projectId: 'havealiens-dcf3e',
    storageBucket: 'havealiens-dcf3e.appspot.com',
    iosBundleId: 'com.example.ai.RunnerTests',
  );
}
